#!/usr/bin/env bash
#sets up load balancers
sudo apt install -y haproxy=1.5\*
file=/etc/haproxy/haproxy.cfg
sudo echo -e "frontend haproxynode
\tbind *:80
\tmode http
\tdefault_backend nodes" | sudo tee -a $file
sudo echo -e "backend nodes
\tmode http
\tbalance roundrobin
\toption forwardfor
\thttp-request set-header X-Forwarded-Port %[dst_port]
\tserver 73664-web-01 54.237.104.123:80 check
\tserver 73664-web-02 54.236.17.102:80 check" | sudo tee -a $file
sudo service haproxy restart
