#!/usr/bin/env bash
# Install haproxy and config 2 server
apt-get update
apt-get -y install haproxy=1.6.\*
echo "ENABLED=1" >> /etc/default/haproxy
sed -i '/504.http/a \\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 73664-web-01 54.237.104.123:80 check\n\tserver 73664-web-02 54.236.17.102:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy start
